//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silhouette.LoadTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using DeviceSimulator;
    using System.IO;
    using System.Resources;
    using System.Diagnostics;

    [DeploymentItem(@"TestState.json", "")]
    [DeploymentItem(@"TestStateUpdated.json", "")]
    public class SilhouetteDeviceLoadTest : WebTest
    {
        DeviceSimulator _device;
        string _testState;
        string _testStateUpdated;
        string _deviceId;
        string _connectionString;

        public SilhouetteDeviceLoadTest()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";


           this.
            _connectionString = (string)this.Context["IoTHubConnectionString"];
            _testState = File.ReadAllText("TestState.json");
            _testStateUpdated = File.ReadAllText("TestStateUpdated.json");


        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            
            Debug.WriteLine("Device:" + this.Context.WebTestUserId);
            _deviceId = "TestDevice-" + this.Context.WebTestUserId;
            _device = new DeviceSimulator(_connectionString, _deviceId);

            if (this.Context.IsNewUser)
            {
                _device.InitializeAsync();
                _device.SendStateMessageAsync(_testState);

            }
            else
            {
                _device.SendStateMessageAsync(_testStateUpdated);
            }

            yield return new WebTestRequest("");
        }
    }
}
