//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silhouette.LoadTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using DeviceSimulator;
    using System.IO;
    using System.Resources;
    using System.Diagnostics;

    
    public class SilhouetteAPILoadTest : WebTest
    {
        string _deviceId;
        string _baseAddress;

        public SilhouetteAPILoadTest()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";

            _baseAddress = "http://localhost:87/v0.1";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            _deviceId = "TestDevice-" + this.Context.WebTestUserId;
          
            Debug.WriteLine("DeviceID:" +_deviceId);
            yield return Call("/devices/" + _deviceId + "/state/latest-reported");
        }

        private WebTestRequest Call(string requestRoute)
        {
            WebTestRequest request = new WebTestRequest(_baseAddress + requestRoute);
            request.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            request.ExpectedHttpStatusCode = 200;
            return request;
        }
    }
}
